name: Build and Deploy ASP.NET Core API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x' # Set the version of .NET you are using

    - name: Restore dependencies
      run: dotnet restore BooknestAPI.sln # Add the correct path here

    - name: Build the solution
      run: dotnet build BooknestAPI.sln --configuration Release --no-restore

    - name: Run tests
      run: dotnet test BooknestAPI.csproj --no-restore --verbosity normal

    - name: Publish the API
      run: dotnet publish BooknestAPI.csproj --configuration Release --output ./publish
